#!/bin/sh
#
# @name COEX Clover 4
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Oleg Kalachev <okalachev@gmail.com>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

param set-default EKF2_AID_MASK 26 # flow + vis pos + vis yaw
param set-default EKF2_OF_DELAY 0
param set-default EKF2_OF_QMIN 10
param set-default EKF2_OF_N_MIN 0.05
param set-default EKF2_OF_N_MAX 0.2
param set-default EKF2_HGT_MODE 2 # range sensor
param set-default EKF2_EVA_NOISE 0.1
param set-default EKF2_EVP_NOISE 0.1
param set-default EKF2_EV_DELAY 0

param set-default ATT_W_EXT_HDG 0.5
param set-default ATT_EXT_HDG_M 1
param set-default ATT_W_MAG 0

param set-default LPE_FLW_SCALE 1.0
param set-default LPE_FLW_R 0.2
param set-default LPE_FLW_RR 0.0
param set-default LPE_FLW_QMIN 10
param set-default LPE_VIS_DELAY 0.0
param set-default LPE_VIS_Z 0.1
param set-default LPE_FUSION 86 # flow + vis + land detector + gyro comp

param set-default SENS_FLOW_ROT 0
param set-default SENS_FLOW_MINHGT 0.0
param set-default SENS_FLOW_MAXHGT 4.0
param set-default SENS_FLOW_MAXR 10.0

param set-default CAL_MAG_SIDES 34 # calibrate mag by 2 sides

param set-default RC_MAP_KILL_SW 5
param set-default RC_MAP_FLTMODE 6

param set-default COM_FLTMODE1 8 # stab
param set-default COM_FLTMODE2 8 # stab
param set-default COM_FLTMODE3 1 # alt
param set-default COM_FLTMODE4 1 # alt
param set-default COM_FLTMODE5 2 # pos
param set-default COM_FLTMODE6 2 # pos
